;;; -*- Mode: LISP; Package: :cl-user; BASE: 10; Syntax: ANSI-Common-Lisp; -*-
;;;
;;;   Time-stamp: <>
;;;   Touched: Wed Mar 26 16:12:56 2025 +0530 <enometh@net.meer>
;;;   Bugs-To: enometh@net.meer
;;;   Status: Experimental.  Do not redistribute
;;;   Copyright (C) 2025 Madhu.  All Rights Reserved.
;;;
;;; Forbear to judge, for we are sinners all.
;;;
(in-package "CL-CLAW-MUPDF")

;; helper
(defmacro def-stext-process-func (container-name contained-name &key access-first access-last
				  &aux (*package* (find-package "CL-CLAW-MUPDF")))
  (let ((type-name (find-symbol (format nil "FZ-STEXT-~A" container-name)))
	(contained-type-name (find-symbol (format nil "FZ-STEXT-~A" contained-name)))
	(first-field-name (find-symbol (format nil "FIRST-~A" contained-name)))
	(last-field-name (find-symbol (format nil "LAST-~A" contained-name)))
	(funcall-arg-name (intern (format nil "~A" contained-name))))
    (let ((first-var (intern (format nil "FIRST-~A" contained-name)))
	  (last-var (intern (format nil "LAST-~A" contained-name)))
	  (arg-name (intern (format nil "STEXT-~A" container-name)))
	  (fun-name (intern (format nil "PROCESS-STEXT-~A" container-name))))
      `(defun ,fun-name (ctx ,arg-name func)
	 ,(format nil "call (FUNC CTX ~A) on every ~A of ~A"
		  funcall-arg-name contained-type-name arg-name)
	 (loop with ,first-var = ,(if access-first
				      `(funcall ,access-first ,arg-name)
				      `(cffi:foreign-slot-value
				       ,arg-name ',type-name ',first-field-name))
	       and ,last-var = ,(if access-last
				    `(funcall ,access-last ,arg-name)
				    `(cffi:foreign-slot-value
				      ,arg-name ',type-name ',last-field-name))
	       for ,funcall-arg-name = ,first-var
	       then (cffi:foreign-slot-value ,funcall-arg-name ',contained-type-name 'next)
	       do (funcall func ctx ,funcall-arg-name)
	       until (cffi:pointer-eq ,funcall-arg-name ,last-var))))))

;; process-stext-page (stext-page)
(def-stext-process-func page block)

#||
(let ((u (cffi:foreign-slot-value $b 'fz-stext-block 'u)))
  u)
||#

(defun stext-block-first-line (stext-block
			       &aux (*package* (find-package "CL-CLAW-MUPDF")))
  (let ((u (cffi:foreign-slot-value stext-block 'FZ-STEXT-BLOCK (intern "U"))))
    ;; 1. pass (intern "U") or the compiler-macro will return a
    ;; pointer for the aggregate union.  2. We don't use union names
    ;; to access the slots as they have random names generated by claw
    ;; wrapper. If we did these functions stext-block-first-line and
    ;; stext-block-next-line wouldn't suck on 2 counts.
    (getf (getf u 'claw-cxx-mupdf:t) 'first-line)))

(defun stext-block-last-line (stext-block
			      &aux (*package* (find-package "CL-CLAW-MUPDF")))
  (let ((u (cffi:foreign-slot-value stext-block 'FZ-STEXT-BLOCK (intern "U"))))
    (getf (getf u 'claw-cxx-mupdf:t) 'last-line)))


;; process-stext-block (stext-block)
(def-stext-process-func block line :access-first 'stext-block-first-line
			:access-last 'stext-block-last-line)

;; process-stext-line (stext-line)
(def-stext-process-func line char)

